language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - sys-img-armeabi-v7a-android-25
    - add-on
    - extra
  licenses:
      - 'android-sdk-license-.+'