language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-24.0.3
    - android-24
    - sys-img-armeabi-v7a-android-24
    - add-on
    - extra
  licenses:
      - 'android-sdk-license-.+'